# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'ZySDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZySDK
  pod 'Alamofire'

  target 'ZySDKTests' do
    # Pods for testing
  end

end
