#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef ZYSDK_SWIFT_H
#define ZYSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreBluetooth;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZySDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)


@class NSString;

SWIFT_CLASS("_TtC5ZySDK18ZyAddressBookModel")
@interface ZyAddressBookModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull phoneNumber;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ZyAlarmType : NSInteger;

SWIFT_CLASS("_TtC5ZySDK12ZyAlarmModel")
@interface ZyAlarmModel : NSObject
@property (nonatomic) BOOL isValid;
@property (nonatomic) NSInteger alarmIndex;
@property (nonatomic) BOOL alarmOpen;
@property (nonatomic) NSInteger alarmHour;
@property (nonatomic) NSInteger alarmMinute;
@property (nonatomic) enum ZyAlarmType alarmType;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nullable alarmRepeatArray;
@property (nonatomic, readonly) NSInteger alarmRepeatCount;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDic:(NSDictionary<NSString *, id> * _Nonnull)dic OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZyAlarmType, open) {
  ZyAlarmTypeSingle = 0,
  ZyAlarmTypeCycle = 1,
};

@class CBUUID;
@class CBPeripheral;
@class ZyFunctionListModel;
@class ZyScanModel;

SWIFT_CLASS("_TtC5ZySDK12ZyBaseModule")
@interface ZyBaseModule : NSObject
/// 已配对设备的UUID数组，用来获取被手机系统配对的设备。默认不获取已被手机配对的设备
@property (nonatomic, copy) NSArray<CBUUID *> * _Nullable matchingUUIDArray;
/// 过滤设备的UUID数组。默认扫描所有设备
@property (nonatomic, copy) NSArray<CBUUID *> * _Nullable serviceUUIDArray;
/// 扫描时间
@property (nonatomic) NSInteger scanInterval;
@property (nonatomic, readonly, strong) CBPeripheral * _Nullable peripheral;
@property (nonatomic, readonly) CBCentralManagerState blePowerState;
@property (nonatomic, readonly, strong) ZyFunctionListModel * _Nullable functionListModel;
@property (nonatomic, readonly) BOOL isSyncOtaData;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 外设连接状态变化回调
/// \param state <#state description#>
///
- (void)peripheralStateChangeWithState:(void (^ _Nonnull)(CBPeripheralState))state;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
/// 蓝牙状态变化回调
/// \param state <#state description#>
///
- (void)bluetoothPowerStateChangeWithState:(void (^ _Nonnull)(CBCentralManagerState))state;
/// ancs共享通知变化回调
/// \param state iOS13及以上才会正常返回
///
- (void)bluetoothAncsStateChangeWithState:(void (^ _Nonnull)(BOOL))state;
/// 设置是否需要重连
/// \param state true:重连 false:不重连
///
- (void)setIsNeedReconnectWithState:(BOOL)state;
/// 重连成功回调
/// \param complete <#complete description#>
///
- (void)reconnectDeviceWithComplete:(void (^ _Nonnull)(void))complete;
/// 获取重连标识
///
/// returns:
/// 外设唯一标识
- (NSString * _Nonnull)getReconnectIdentifier SWIFT_WARN_UNUSED_RESULT;
/// 获取系统列表的设备
/// \param modelArray <#modelArray description#>
///
- (void)getSystemListPeripheralWithModelArray:(void (^ _Nonnull)(NSArray<ZyScanModel *> * _Nonnull))modelArray;
/// 扫描设备，每新增一个设备都会有回调
/// \param scanModel 扫描到的设备
///
/// \param modelArray 所有扫描到的设备数组，包括系统蓝牙列表已连接的
///
///
/// returns:
///
- (void)scanDeviceWithScanModel:(void (^ _Nonnull)(ZyScanModel * _Nonnull))scanModel modelArray:(void (^ _Nonnull)(NSArray<ZyScanModel *> * _Nonnull))modelArray;
/// 停止扫描
- (void)stopScan;
/// 连接设备
/// \param peripheral 支持String跟CBPeripheral两种
///
/// \param connectState 连接状态
///
///
/// returns:
///
- (void)connectDeviceWithPeripheral:(id _Nonnull)peripheral connectState:(void (^ _Nonnull)(BOOL))connectState;
/// 断开连接
- (void)disconnect;
- (NSArray<NSNumber *> * _Nonnull)getNotificationExtensionTypeArrayWithIntStringWithCountString:(NSString * _Nonnull)countString SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSNumber *> * _Nonnull)getNotificationTypeArrayWithIntStringWithCountString:(NSString * _Nonnull)countString SWIFT_WARN_UNUSED_RESULT;
@end

enum ZyError : NSInteger;
@class ZyPersonalModel;
@class ZyWeatherModel;
enum ZyExerciseType : NSInteger;
enum ZyExerciseState : NSInteger;
@class ZyCustomDialModel;
@class UIColor;
@class UIImage;
@class ZyDialFrameSizeModel;
@class ZySedentaryModel;
@class ZyStartEndTimeModel;
@class ZyDoNotDisturbModel;
@class ZyHrWaringModel;
@class ZyMenstrualModel;
@class ZyDrinkWaterModel;
@class ZyLowBatteryModel;
@class ZyWorshipTimeModel;
@class ZyExerciseModel;
@class ZyStepModel;
@class CLLocation;
@class ZyLedFunctionModel;
enum ZyLedFunctionType : NSInteger;
@class ZyMotorFunctionModel;
@class ZyOnlineDialModel;

SWIFT_CLASS("_TtC5ZySDK15ZyCommandModule")
@interface ZyCommandModule : ZyBaseModule
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZyCommandModule * _Nonnull shareInstance;)
+ (ZyCommandModule * _Nonnull)shareInstance SWIFT_WARN_UNUSED_RESULT;
- (BOOL)checkCurrentCommamdIsNeedWait SWIFT_WARN_UNUSED_RESULT;
- (void)resetWaitCommand;
- (void)getDeviceName:(void (^ _Nonnull)(NSString * _Nullable, enum ZyError))success;
- (void)getFirmwareVersion:(void (^ _Nonnull)(NSString * _Nullable, enum ZyError))success;
- (void)getSerialNumber:(void (^ _Nonnull)(NSString * _Nullable, enum ZyError))success;
- (void)getMac:(void (^ _Nonnull)(NSString * _Nullable, enum ZyError))success;
- (void)getBattery:(void (^ _Nonnull)(NSString * _Nullable, enum ZyError))success;
- (void)setTimeWithTime:(id _Nullable)time success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getDeviceOtaVersionInfo:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull, enum ZyError))success;
- (void)getPersonalInformation:(void (^ _Nonnull)(ZyPersonalModel * _Nullable, enum ZyError))success;
- (void)setPersonalInformationWithModel:(ZyPersonalModel * _Nonnull)model success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getTimeFormat:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)setTimeFormatWithFormat:(NSInteger)format success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getMetricSystem:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)setMetricSystemWithMetric:(NSInteger)metric success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setWeatherWithModel:(ZyWeatherModel * _Nonnull)model updateTime:(NSString * _Nullable)updateTime success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setEnterCameraWithSuccess:(void (^ _Nonnull)(enum ZyError))success;
- (void)setFindDeviceWithSuccess:(void (^ _Nonnull)(enum ZyError))success;
- (void)getLightScreen:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)setLightScreenWithIsOpen:(NSInteger)isOpen success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getScreenLevel:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)setScreenLevelWithValue:(NSInteger)value success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getScreenTimeLong:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)setScreenTimeLongWithValue:(NSInteger)value success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getLocalDial:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)setLocalDialWithIndex:(NSInteger)index success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getAlarmWithIndex:(NSInteger)index success:(void (^ _Nonnull)(ZyAlarmModel * _Nullable, enum ZyError))success;
- (void)setAlarmWithIndex:(NSString * _Nonnull)index repeatCount:(NSString * _Nonnull)repeatCount hour:(NSString * _Nonnull)hour minute:(NSString * _Nonnull)minute success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setAlarmModelWithModel:(ZyAlarmModel * _Nonnull)model success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getDeviceLanguage:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)setDeviceLanguageWithIndex:(NSInteger)index success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getStepGoal:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)setStepGoalWithTarget:(NSInteger)target success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getDispalyMode:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)setDispalyModeWithIsVertical:(NSInteger)isVertical success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getWearingWay:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)setWearingWayWithIsLeftHand:(NSInteger)isLeftHand success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setSingleMeasurementWithType:(NSInteger)type isOpen:(NSInteger)isOpen success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getExerciseMode:(void (^ _Nonnull)(enum ZyExerciseType, enum ZyExerciseState, enum ZyError))success;
- (void)setExerciseModeWithType:(enum ZyExerciseType)type isOpen:(enum ZyExerciseState)isOpen timestamp:(NSInteger)timestamp success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setDeviceModeWithType:(NSInteger)type isOpen:(NSInteger)isOpen success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setPhoneModeWithType:(NSInteger)type success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getWeatherUnit:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)setWeatherUnitWithType:(NSInteger)type success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setReportRealtimeDataWithIsOpen:(NSInteger)isOpen success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getCustomDialEdit:(void (^ _Nonnull)(ZyCustomDialModel * _Nullable, enum ZyError))success;
- (void)setCustomDialEditWithColor:(UIColor * _Nonnull)color positionType:(NSString * _Nonnull)positionType timeUpType:(NSString * _Nonnull)timeUpType timeDownType:(NSString * _Nonnull)timeDownType success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setCustomDialEditWithModel:(ZyCustomDialModel * _Nonnull)model success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setCustomDialEditWithImage:(UIImage * _Nonnull)image progress:(void (^ _Nonnull)(float))progress success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setCustomDialEditWithImage:(UIImage * _Nonnull)image progress:(void (^ _Nonnull)(float))progress isJL_Device:(BOOL)isJL_Device success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setPhoneStateWithState:(NSString * _Nonnull)state success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getCustonDialFrameSize:(void (^ _Nonnull)(ZyDialFrameSizeModel * _Nullable, enum ZyError))success;
- (void)get24HrMonitor:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)set24HrMonitorWithIsOpen:(NSInteger)isOpen success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setEnterOrExitCameraWithIsOpen:(NSInteger)isOpen success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setDeviceUUIDWithUuidString:(NSString * _Nullable)uuidString success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setExerciseDataToDeviceWithType:(enum ZyExerciseType)type timeLong:(NSInteger)timeLong calories:(NSInteger)calories distance:(NSInteger)distance success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setClearAllData:(void (^ _Nonnull)(enum ZyError))success;
- (void)setBind:(void (^ _Nonnull)(enum ZyError))success;
- (void)setUnbind:(void (^ _Nonnull)(enum ZyError))success;
- (void)getNotificationRemind:(void (^ _Nonnull)(NSArray<NSNumber *> * _Nonnull, NSArray<NSNumber *> * _Nonnull, enum ZyError))success;
- (void)setNotificationRemindWithIsOpen:(NSString * _Nonnull)isOpen extensionOpen:(NSString * _Nonnull)extensionOpen success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setNotificationRemindArrayWithArray:(NSArray<NSNumber *> * _Nonnull)array extensionArray:(NSArray<NSNumber *> * _Nonnull)extensionArray success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getSedentary:(void (^ _Nonnull)(ZySedentaryModel * _Nullable, enum ZyError))success;
- (void)setSedentaryWithIsOpen:(NSString * _Nonnull)isOpen timeLong:(NSString * _Nonnull)timeLong timeArray:(NSArray<ZyStartEndTimeModel *> * _Nonnull)timeArray success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setSedentaryWithModel:(ZySedentaryModel * _Nonnull)model success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setSedentaryWithIsOpen:(NSString * _Nonnull)isOpen timeLong:(NSString * _Nonnull)timeLong startHour:(NSString * _Nonnull)startHour startMinute:(NSString * _Nonnull)startMinute endHour:(NSString * _Nonnull)endHour endMinute:(NSString * _Nonnull)endMinute success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getLost:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)setLostWithIsOpen:(NSString * _Nonnull)isOpen success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getDoNotDisturb:(void (^ _Nonnull)(ZyDoNotDisturbModel * _Nullable, enum ZyError))success;
- (void)setDoNotDisturbWithIsOpen:(NSString * _Nonnull)isOpen startHour:(NSString * _Nonnull)startHour startMinute:(NSString * _Nonnull)startMinute endHour:(NSString * _Nonnull)endHour endMinute:(NSString * _Nonnull)endMinute success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setDoNotDisturbWithModel:(ZyDoNotDisturbModel * _Nonnull)model success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getHrWaring:(void (^ _Nonnull)(ZyHrWaringModel * _Nullable, enum ZyError))success;
- (void)setHrWaringWithIsOpen:(NSString * _Nonnull)isOpen maxHr:(NSString * _Nonnull)maxHr minHr:(NSString * _Nonnull)minHr success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setHrWaringWithModel:(ZyHrWaringModel * _Nonnull)model success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getMenstrualCycle:(void (^ _Nonnull)(ZyMenstrualModel * _Nullable, enum ZyError))success;
- (void)setMenstrualCycleWithModel:(ZyMenstrualModel * _Nonnull)model success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setMenstrualCycleWithIsOpen:(NSString * _Nonnull)isOpen cycleCount:(NSString * _Nonnull)cycleCount menstrualCount:(NSString * _Nonnull)menstrualCount year:(NSString * _Nonnull)year month:(NSString * _Nonnull)month day:(NSString * _Nonnull)day advanceDay:(NSString * _Nonnull)advanceDay remindHour:(NSString * _Nonnull)remindHour remindMinute:(NSString * _Nonnull)remindMinute success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getWashHand:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull, enum ZyError))success;
- (void)setWashHandWithIsOpen:(NSString * _Nonnull)isOpen startHour:(NSString * _Nonnull)startHour startMinute:(NSString * _Nonnull)startMinute targetCount:(NSString * _Nonnull)targetCount remindInterval:(NSString * _Nonnull)remindInterval success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getDrinkWater:(void (^ _Nonnull)(ZyDrinkWaterModel * _Nullable, enum ZyError))success;
- (void)setDrinkWaterWithIsOpen:(NSString * _Nonnull)isOpen startHour:(NSString * _Nonnull)startHour startMinute:(NSString * _Nonnull)startMinute endHour:(NSString * _Nonnull)endHour endMinute:(NSString * _Nonnull)endMinute remindInterval:(NSString * _Nonnull)remindInterval success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setDrinkWaterWithModel:(ZyDrinkWaterModel * _Nonnull)model success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setAddressBookWithModelArray:(NSArray<ZyAddressBookModel *> * _Nonnull)modelArray success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getLowBatteryRemind:(void (^ _Nonnull)(ZyLowBatteryModel * _Nullable, enum ZyError))success;
- (void)setLowBatteryRemindWithIsOpen:(NSString * _Nonnull)isOpen remindBattery:(NSString * _Nonnull)remindBattery remindCount:(NSString * _Nonnull)remindCount remindInterval:(NSString * _Nonnull)remindInterval success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setLowBatteryRemindWithModel:(ZyLowBatteryModel * _Nonnull)model success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setWorshipTime:(NSArray<ZyWorshipTimeModel *> * _Nonnull)modelArray progress:(void (^ _Nonnull)(float))progress success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setLocalMusicFile:(NSString * _Nonnull)fileNmae localFile:(id _Nonnull)localFile progress:(void (^ _Nonnull)(float))progress success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setSyncHealthDataWithType:(NSString * _Nonnull)type dayCount:(NSString * _Nonnull)dayCount success:(void (^ _Nonnull)(id _Nullable, enum ZyError))success;
- (void)setSyncExerciseDataWithIndexCount:(NSInteger)indexCount success:(void (^ _Nonnull)(ZyExerciseModel * _Nullable, enum ZyError))success;
- (void)getDeviceSupportList:(void (^ _Nonnull)(ZyFunctionListModel * _Nullable, enum ZyError))success;
- (void)setPowerTurnOffWithSuccess:(void (^ _Nonnull)(enum ZyError))success;
- (void)setFactoryDataResetWithSuccess:(void (^ _Nonnull)(enum ZyError))success;
- (void)setMotorVibrationWithType:(NSString * _Nonnull)type success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setRestartWithSuccess:(void (^ _Nonnull)(enum ZyError))success;
- (void)setFactoryAndPowerOffWithSuccess:(void (^ _Nonnull)(enum ZyError))success;
- (void)reportRealTimeStepWithSuccess:(void (^ _Nonnull)(ZyStepModel * _Nullable, enum ZyError))success;
- (void)reportRealTimeHrWithSuccess:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull, enum ZyError))success;
- (void)reportSingleMeasurementResultWithSuccess:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull, enum ZyError))success;
- (void)reportExerciseStateWithSuccess:(void (^ _Nonnull)(enum ZyExerciseState, enum ZyError))success;
- (void)reportFindPhoneWithSuccess:(void (^ _Nonnull)(enum ZyError))success;
- (void)reportEndFindPhoneWithSuccess:(void (^ _Nonnull)(enum ZyError))success;
- (void)reportTakePicturesWithSuccess:(void (^ _Nonnull)(enum ZyError))success;
- (void)reportEnterOrExitCameraWithSuccess:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)reportMusicControlWithSuccess:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)reportCallControlWithSuccess:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)reportScreenLevelWithSuccess:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)reportScreenTimeLongWithSuccess:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)reportLightScreenWithSuccess:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)reportDeviceVibrationWithSuccess:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)reportNewRealtimeDataWithSuccess:(void (^ _Nonnull)(ZyStepModel * _Nullable, NSInteger, NSInteger, NSInteger, NSInteger, enum ZyError))success;
- (void)reportExerciseInteractionDataWithSuccess:(void (^ _Nonnull)(NSInteger, NSInteger, NSInteger, enum ZyError))success;
- (void)reportDoNotDisturbWithSuccess:(void (^ _Nonnull)(ZyDoNotDisturbModel * _Nullable, enum ZyError))success;
/// 同步数据
/// \param type 1：步数，2：心率，3：睡眠，4、锻炼数据
///
/// \param indexArray <#indexArray description#>
///
/// \param success <#success description#>
///
- (void)setNewSyncHealthDataWithType:(NSInteger)type indexArray:(NSArray<NSNumber *> * _Nonnull)indexArray success:(void (^ _Nonnull)(id _Nullable, enum ZyError))success;
/// 同步数据
/// \param dataType 1：心率，2：血氧，3：血压，4：血糖，5：压力，6.体温，7：心电，
///
/// \param measureType 1：全天测量 ，2：点击测量
///
/// \param indexArray <#indexArray description#>
///
/// \param success <#success description#>
///
- (void)setSyncMeasurementDataWithDataType:(NSInteger)dataType measureType:(NSInteger)measureType indexArray:(NSArray<NSNumber *> * _Nonnull)indexArray success:(void (^ _Nonnull)(id _Nullable, enum ZyError))success;
- (void)setNewWeatherWithModelArray:(NSArray<ZyWeatherModel *> * _Nonnull)modelArray updateTime:(NSString * _Nullable)updateTime success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setNewAlarmArrayWithModelArray:(NSArray<ZyAlarmModel *> * _Nonnull)modelArray success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getNewAlarmArrayWithSuccess:(void (^ _Nonnull)(NSArray<ZyAlarmModel *> * _Nonnull, enum ZyError))success;
- (void)setSleepGoalWithTarget:(NSInteger)target success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getSleepGoal:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)setSosContactPersonWithModel:(ZyAddressBookModel * _Nonnull)model success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getSosContactPerson:(void (^ _Nonnull)(ZyAddressBookModel * _Nullable, enum ZyError))success;
/// \param type 1：心率，2：血氧，3：血压，4：血糖，5：压力，6.体温，7：心电，
///
/// \param isOpen 0：关 1：开
///
/// \param timeInterval 开关为开必须>0
///
- (void)setCycleMeasurementParametersWithType:(NSInteger)type isOpen:(NSInteger)isOpen timeInterval:(NSInteger)timeInterval success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getWorshipStartTime:(void (^ _Nonnull)(NSString * _Nullable, NSInteger, enum ZyError))success;
- (void)reportWorshipStartTimeWithSuccess:(void (^ _Nonnull)(NSString * _Nullable, NSInteger, enum ZyError))success;
- (void)reportAlarmArrayWithSuccess:(void (^ _Nonnull)(NSArray<ZyAlarmModel *> * _Nonnull, enum ZyError))success;
/// \param timeZone 0-12东区 13-24西区  （正数不变负数从13开始）
///
- (void)setTimeZoneWithTimeZone:(NSInteger)timeZone success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getAssistedPositioningState:(void (^ _Nonnull)(NSInteger, enum ZyError))success;
- (void)reportLocationInfoWithSuccess:(void (^ _Nonnull)(enum ZyError))success;
- (void)setLocationInfoWithLocaltion:(CLLocation * _Nonnull)localtion;
- (void)setLedSetupWithModelArray:(NSArray<ZyLedFunctionModel *> * _Nonnull)modelArray success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getLedSetup:(void (^ _Nonnull)(NSArray<ZyLedFunctionModel *> * _Nonnull, enum ZyError))success;
- (void)getLedSetupWithType:(enum ZyLedFunctionType)type success:(void (^ _Nonnull)(ZyLedFunctionModel * _Nullable, enum ZyError))success;
- (void)setLedSetupWithModel:(ZyLedFunctionModel * _Nonnull)model success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getMotorShakeFunctionWithType:(enum ZyLedFunctionType)type success:(void (^ _Nonnull)(ZyMotorFunctionModel * _Nullable, enum ZyError))success;
- (void)setMotorShakeFunctionWithModel:(ZyMotorFunctionModel * _Nonnull)model success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setMotorShakeFunctionWithModelArray:(NSArray<ZyMotorFunctionModel *> * _Nonnull)modelArray success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getMotorShakeFunction:(void (^ _Nonnull)(NSArray<ZyMotorFunctionModel *> * _Nonnull, enum ZyError))success;
- (void)setOtaStartUpgradeWithType:(NSInteger)type localFile:(id _Nonnull)localFile isContinue:(BOOL)isContinue progress:(void (^ _Nonnull)(float))progress success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setSubpackageInformationInteractionWithMaxSend:(NSInteger)maxSend maxReceive:(NSInteger)maxReceive success:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull, enum ZyError))success;
- (void)replySubpackageInformationInteractionWithState:(NSInteger)state maxSend:(NSInteger)maxSend maxReceive:(NSInteger)maxReceive success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setStartUpgradeWithType:(NSInteger)type localFile:(id _Nonnull)localFile maxCount:(NSInteger)maxCount isContinue:(BOOL)isContinue progress:(void (^ _Nonnull)(float))progress success:(void (^ _Nonnull)(enum ZyError))success;
- (void)setStopUpgradeWithSuccess:(void (^ _Nonnull)(enum ZyError))success;
- (void)checkUpgradeStateWithSuccess:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull, enum ZyError))success;
- (void)getServerOtaDeviceInfoWithSuccess:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull, enum ZyError))success;
- (void)setAutoServerOtaDeviceInfoWithUrl:(NSString * _Nullable)url progress:(void (^ _Nonnull)(float))progress success:(void (^ _Nonnull)(enum ZyError))success;
- (void)getLocalDialImageServerInfoWithSuccess:(void (^ _Nonnull)(NSArray<NSDictionary<NSString *, id> *> * _Nullable, enum ZyError))success;
- (void)getCustomDialImageServerInfoWithSuccess:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nullable, enum ZyError))success;
- (void)getOnlineDialListWithSuccess:(void (^ _Nonnull)(NSArray<ZyOnlineDialModel *> * _Nonnull, enum ZyError))success;
- (void)getOnlineDialListWithPageIndex:(NSInteger)pageIndex pageSize:(NSInteger)pageSize success:(void (^ _Nonnull)(NSArray<ZyOnlineDialModel *> * _Nonnull, enum ZyError))success;
- (void)setOnlienDialFileWithModel:(id _Nonnull)model progress:(void (^ _Nonnull)(float))progress success:(void (^ _Nonnull)(enum ZyError))success;
- (void)testMultiplePackagesWithCmdClass:(NSInteger)cmdClass cmdId:(NSInteger)cmdId totalLength:(NSInteger)totalLength subpackageLength:(NSInteger)subpackageLength;
- (void)testUtf8StringDataWithCmdClass:(NSInteger)cmdClass cmdId:(NSInteger)cmdId type:(NSString * _Nonnull)type sendString:(NSString * _Nonnull)sendString;
- (void)testUnicodeStringDataWithCmdClass:(NSInteger)cmdClass cmdId:(NSInteger)cmdId type:(NSString * _Nonnull)type sendString:(NSString * _Nonnull)sendString;
@end

enum ZyPositionType : NSInteger;
enum ZyPositionShowType : NSInteger;

SWIFT_CLASS("_TtC5ZySDK17ZyCustomDialModel")
@interface ZyCustomDialModel : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull colorHex;
@property (nonatomic, strong) UIColor * _Nonnull color;
@property (nonatomic) enum ZyPositionType positionType;
@property (nonatomic) enum ZyPositionShowType timeUpType;
@property (nonatomic) enum ZyPositionShowType timeDownType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5ZySDK20ZyDialFrameSizeModel")
@interface ZyDialFrameSizeModel : NSObject
@property (nonatomic, readonly) NSInteger bigWidth;
@property (nonatomic, readonly) NSInteger bigHeight;
@property (nonatomic, readonly) NSInteger smallWidth;
@property (nonatomic, readonly) NSInteger smallHeight;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5ZySDK19ZyDoNotDisturbModel")
@interface ZyDoNotDisturbModel : NSObject
@property (nonatomic) BOOL isOpen;
@property (nonatomic, strong) ZyStartEndTimeModel * _Nonnull timeModel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5ZySDK17ZyDrinkWaterModel")
@interface ZyDrinkWaterModel : NSObject
@property (nonatomic) BOOL isOpen;
@property (nonatomic) NSInteger remindInterval;
@property (nonatomic, strong) ZyStartEndTimeModel * _Nonnull timeModel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZyError, open) {
  ZyErrorNone = 0,
  ZyErrorDisconnected = 1,
  ZyErrorInvalidCharacteristic = 2,
  ZyErrorInvalidLength = 3,
  ZyErrorInvalidState = 4,
  ZyErrorNotSupport = 5,
  ZyErrorNoResponse = 6,
  ZyErrorNoMoreData = 7,
  ZyErrorFail = 8,
};


SWIFT_CLASS("_TtC5ZySDK15ZyExerciseModel")
@interface ZyExerciseModel : NSObject
@property (nonatomic) enum ZyExerciseType type;
@property (nonatomic, copy) NSString * _Nonnull startTime;
@property (nonatomic, copy) NSString * _Nonnull endTime;
@property (nonatomic) NSInteger validTimeLength;
@property (nonatomic) NSInteger heartrate;
@property (nonatomic) NSInteger step;
@property (nonatomic) NSInteger calorie;
@property (nonatomic) NSInteger distance;
@property (nonatomic, copy) NSArray<NSArray<CLLocation *> *> * _Nonnull gpsArray;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZyExerciseState, open) {
  ZyExerciseStateUnknow = -1,
  ZyExerciseStateEnd = 0,
  ZyExerciseStateStart = 1,
  ZyExerciseStateContinue = 2,
  ZyExerciseStatePause = 3,
};

typedef SWIFT_ENUM(NSInteger, ZyExerciseType, open) {
  ZyExerciseTypeRunOutside = 0,
  ZyExerciseTypeWalk = 1,
  ZyExerciseTypeCycling = 2,
  ZyExerciseTypeBasketball = 3,
  ZyExerciseTypeFootball = 4,
  ZyExerciseTypeBadminton = 5,
  ZyExerciseTypeJumpRope = 6,
  ZyExerciseTypeSwimming = 7,
  ZyExerciseTypeRunIndoor = 8,
  ZyExerciseTypeVolleyball = 9,
  ZyExerciseTypeWalkFast = 10,
  ZyExerciseTypeSpinning = 11,
  ZyExerciseTypeSitUps = 12,
  ZyExerciseTypeMountainClimbing = 13,
  ZyExerciseTypeYoga = 14,
  ZyExerciseTypeDance = 15,
  ZyExerciseTypeJumpingJacks = 16,
  ZyExerciseTypeGymnastics = 17,
  ZyExerciseTypeRowing = 18,
  ZyExerciseTypeTennis = 19,
  ZyExerciseTypeHockey = 20,
  ZyExerciseTypeBaseball = 21,
  ZyExerciseTypeTableTennis = 22,
  ZyExerciseTypeCricket = 23,
  ZyExerciseTypeRugby = 24,
};

@class ZyFunctionModel_exercise;
@class ZyFunctionModel_notification;
@class ZyFunctionModel_language;
@class ZyFunctionModel_alarm;
@class ZyFunctionModel_screenControl;
@class ZyFunctionModel_addressBook;
@class ZyFunctionModel_localDial;
@class ZyFunctionModel_hrWarning;
@class ZyFunctionModel_goal;
@class ZyFunctionModel_scrrenType;
@class ZyFunctionModel_sportCountdown;
@class ZyFunctionModel_platformType;
@class ZyFunctionModel_customDial;
@class ZyFunctionModel_supportMeasurementDataTypeModel;
@class ZyFunctionModel_supportMusicFileTypeModel;

SWIFT_CLASS("_TtC5ZySDK19ZyFunctionListModel")
@interface ZyFunctionListModel : NSObject
@property (nonatomic, readonly) BOOL functionList_exercise;
@property (nonatomic, readonly) BOOL functionList_step;
@property (nonatomic, readonly) BOOL functionList_sleep;
@property (nonatomic, readonly) BOOL functionList_heartrate;
@property (nonatomic, readonly) BOOL functionList_bloodPressure;
@property (nonatomic, readonly) BOOL functionList_bloodOxygen;
@property (nonatomic, readonly) BOOL functionList_notification;
@property (nonatomic, readonly) BOOL functionList_metricSystem;
@property (nonatomic, readonly) BOOL functionList_alarm;
@property (nonatomic, readonly) BOOL functionList_sedentary;
@property (nonatomic, readonly) BOOL functionList_goal;
@property (nonatomic, readonly) BOOL functionList_vibration;
@property (nonatomic, readonly) BOOL functionList_noDisturb;
@property (nonatomic, readonly) BOOL functionList_lost;
@property (nonatomic, readonly) BOOL functionList_weather;
@property (nonatomic, readonly) BOOL functionList_language;
@property (nonatomic, readonly) BOOL functionList_screenConreol;
@property (nonatomic, readonly) BOOL functionList_addressBook;
@property (nonatomic, readonly) BOOL functionList_onlineDial;
@property (nonatomic, readonly) BOOL functionList_customDial;
@property (nonatomic, readonly) BOOL functionList_localDial;
@property (nonatomic, readonly) BOOL functionList_hrWarning;
@property (nonatomic, readonly) BOOL functionList_menstrualCycle;
@property (nonatomic, readonly) BOOL functionList_drinkWater;
@property (nonatomic, readonly) BOOL functionList_lightScreen;
@property (nonatomic, readonly) BOOL functionList_hrMonitor;
@property (nonatomic, readonly) BOOL functionList_camera;
@property (nonatomic, readonly) BOOL functionList_musicControl;
@property (nonatomic, readonly) BOOL functionList_findDevice;
@property (nonatomic, readonly) BOOL functionList_powerOff;
@property (nonatomic, readonly) BOOL functionList_restart;
@property (nonatomic, readonly) BOOL functionList_restoreFactory;
@property (nonatomic, readonly) BOOL functionList_ringOff;
@property (nonatomic, readonly) BOOL functionList_answerCalls;
@property (nonatomic, readonly) BOOL functionList_timeFormat;
@property (nonatomic, readonly) BOOL functionList_screenType;
@property (nonatomic, readonly) BOOL functionList_sportCountdown;
@property (nonatomic, readonly) BOOL functionList_lowBattery;
@property (nonatomic, readonly) BOOL functionList_exerciseInteraction;
@property (nonatomic, readonly) BOOL functionList_clearData;
@property (nonatomic, readonly) BOOL functionList_bind;
@property (nonatomic, readonly) BOOL functionList_weatherExtend;
@property (nonatomic, readonly) BOOL functionList_newPortocol;
@property (nonatomic, readonly) BOOL functionList_platformType;
@property (nonatomic, readonly) BOOL functionList_bloodSugar;
@property (nonatomic, readonly) BOOL functionList_pressure;
@property (nonatomic, readonly) BOOL functionList_electrocardiogram;
@property (nonatomic, readonly) BOOL functionList_bodyTemperature;
@property (nonatomic, readonly) BOOL functionList_sosContactPerson;
@property (nonatomic, readonly) BOOL functionList_worshipAlarm;
@property (nonatomic, readonly) BOOL functionList_localPlay;
@property (nonatomic, readonly, strong) ZyFunctionModel_exercise * _Nullable functionDetail_exercise;
@property (nonatomic, readonly, strong) ZyFunctionModel_notification * _Nullable functionDetail_notification;
@property (nonatomic, readonly, strong) ZyFunctionModel_language * _Nullable functionDetail_language;
@property (nonatomic, readonly, strong) ZyFunctionModel_alarm * _Nullable functionDetail_alarm;
@property (nonatomic, readonly, strong) ZyFunctionModel_screenControl * _Nullable functionDetail_screenControl;
@property (nonatomic, readonly, strong) ZyFunctionModel_addressBook * _Nullable functionDetail_addressBook;
@property (nonatomic, readonly, strong) ZyFunctionModel_localDial * _Nullable functionDetail_localDial;
@property (nonatomic, readonly, strong) ZyFunctionModel_hrWarning * _Nullable functionDetail_hrWarning;
@property (nonatomic, readonly, strong) ZyFunctionModel_goal * _Nullable functionDetail_goal;
@property (nonatomic, readonly, strong) ZyFunctionModel_scrrenType * _Nullable functionDetail_screenType;
@property (nonatomic, readonly, strong) ZyFunctionModel_sportCountdown * _Nullable functionDetail_sportCountdown;
@property (nonatomic, readonly, strong) ZyFunctionModel_platformType * _Nullable functionDetail_platformType;
@property (nonatomic, readonly, strong) ZyFunctionModel_customDial * _Nullable functionDetail_customDial;
@property (nonatomic, readonly, strong) ZyFunctionModel_supportMeasurementDataTypeModel * _Nullable functionDetail_heartrate;
@property (nonatomic, readonly, strong) ZyFunctionModel_supportMeasurementDataTypeModel * _Nullable functionDetail_bloodPressure;
@property (nonatomic, readonly, strong) ZyFunctionModel_supportMeasurementDataTypeModel * _Nullable functionDetail_bloodOxygen;
@property (nonatomic, readonly, strong) ZyFunctionModel_supportMeasurementDataTypeModel * _Nullable functionDetail_bloodSugar;
@property (nonatomic, readonly, strong) ZyFunctionModel_supportMeasurementDataTypeModel * _Nullable functionDetail_pressure;
@property (nonatomic, readonly, strong) ZyFunctionModel_supportMeasurementDataTypeModel * _Nullable functionDetail_electrocardiogram;
@property (nonatomic, readonly, strong) ZyFunctionModel_supportMeasurementDataTypeModel * _Nullable functionDetail_bodyTemperature;
@property (nonatomic, readonly, strong) ZyFunctionModel_supportMusicFileTypeModel * _Nullable functionDetail_localPlay;
- (NSString * _Nonnull)showAllSupportFunctionLog SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ZyFunctionListType, open) {
  ZyFunctionListTypeExercise = 0,
  ZyFunctionListTypeStep = 1,
  ZyFunctionListTypeSleep = 2,
  ZyFunctionListTypeHeartrate = 3,
  ZyFunctionListTypeBloodPressure = 4,
  ZyFunctionListTypeBloodOxygen = 5,
  ZyFunctionListTypeNotification = 6,
  ZyFunctionListTypeMetricSystem = 7,
  ZyFunctionListTypeAlarm = 8,
  ZyFunctionListTypeSedentary = 9,
  ZyFunctionListTypeGoal = 10,
  ZyFunctionListTypeVibration = 11,
  ZyFunctionListTypeNoDisturb = 12,
  ZyFunctionListTypeLost = 13,
  ZyFunctionListTypeWeather = 14,
  ZyFunctionListTypeLanguage = 15,
  ZyFunctionListTypeScreenConreol = 16,
  ZyFunctionListTypeAddressBook = 17,
  ZyFunctionListTypeOnlineDial = 18,
  ZyFunctionListTypeCustomDial = 19,
  ZyFunctionListTypeLocalDial = 20,
  ZyFunctionListTypeHrWarning = 21,
  ZyFunctionListTypeMenstrualCycle = 22,
  ZyFunctionListTypeDrinkWater = 23,
  ZyFunctionListTypeLightScreen = 24,
  ZyFunctionListTypeHrMonitor = 25,
  ZyFunctionListTypeCamera = 26,
  ZyFunctionListTypeMusicControl = 27,
  ZyFunctionListTypeFindDevice = 28,
  ZyFunctionListTypePowerOff = 29,
  ZyFunctionListTypeRestart = 30,
  ZyFunctionListTypeRestoreFactory = 31,
  ZyFunctionListTypeRingOff = 32,
  ZyFunctionListTypeAnswerCalls = 33,
  ZyFunctionListTypeTimeFormat = 34,
  ZyFunctionListTypeScreenType = 35,
  ZyFunctionListTypeSportCountdown = 37,
  ZyFunctionListTypeLowBattery = 38,
  ZyFunctionListTypeExerciseInteraction = 39,
};


SWIFT_CLASS("_TtC5ZySDK27ZyFunctionModel_addressBook")
@interface ZyFunctionModel_addressBook : NSObject
@property (nonatomic, readonly) NSInteger maxContactCount;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK21ZyFunctionModel_alarm")
@interface ZyFunctionModel_alarm : NSObject
@property (nonatomic, readonly) NSInteger maxAlarmCount;
@property (nonatomic, readonly) BOOL isSupportEdit;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK26ZyFunctionModel_customDial")
@interface ZyFunctionModel_customDial : NSObject
@property (nonatomic, readonly) BOOL isSupportfontColor;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK24ZyFunctionModel_exercise")
@interface ZyFunctionModel_exercise : NSObject
@property (nonatomic, readonly) BOOL isSupportRunOutside;
@property (nonatomic, readonly) BOOL isSupportWalk;
@property (nonatomic, readonly) BOOL isSupportCycling;
@property (nonatomic, readonly) BOOL isSupportBasketball;
@property (nonatomic, readonly) BOOL isSupportFootball;
@property (nonatomic, readonly) BOOL isSupportBadminton;
@property (nonatomic, readonly) BOOL isSupportJumpRope;
@property (nonatomic, readonly) BOOL isSupportSwimming;
@property (nonatomic, readonly) BOOL isSupportRunIndoor;
@property (nonatomic, readonly) BOOL isSupportVolleyball;
@property (nonatomic, readonly) BOOL isSupportWalkFast;
@property (nonatomic, readonly) BOOL isSupportSpinning;
@property (nonatomic, readonly) BOOL isSupportSitUps;
@property (nonatomic, readonly) BOOL isSupportMountainClimbing;
@property (nonatomic, readonly) BOOL isSupportYoga;
@property (nonatomic, readonly) BOOL isSupportDance;
@property (nonatomic, readonly) BOOL isSupportJumpingJacks;
@property (nonatomic, readonly) BOOL isSupportGymnastics;
@property (nonatomic, readonly) BOOL isSupportRowing;
@property (nonatomic, readonly) BOOL isSupportTennis;
@property (nonatomic, readonly) BOOL isSupportHockey;
@property (nonatomic, readonly) BOOL isSupportBaseball;
@property (nonatomic, readonly) BOOL isSupportTableTennis;
@property (nonatomic, readonly) BOOL isSupportCricket;
@property (nonatomic, readonly) BOOL isSupportRugby;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK20ZyFunctionModel_goal")
@interface ZyFunctionModel_goal : NSObject
@property (nonatomic, readonly) BOOL isSupportStep;
@property (nonatomic, readonly) BOOL isSupportSleep;
@property (nonatomic, readonly) BOOL isSupportCalorie;
@property (nonatomic, readonly) BOOL isSupportTimeLong;
@property (nonatomic, readonly) BOOL isSupportDistance;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK25ZyFunctionModel_hrWarning")
@interface ZyFunctionModel_hrWarning : NSObject
@property (nonatomic, readonly) NSInteger maxValue;
@property (nonatomic, readonly) NSInteger minValue;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK24ZyFunctionModel_language")
@interface ZyFunctionModel_language : NSObject
@property (nonatomic, readonly) BOOL isSupportEnglish;
@property (nonatomic, readonly) BOOL isSupportSimplifiedChinese;
@property (nonatomic, readonly) BOOL isSupportJapan;
@property (nonatomic, readonly) BOOL isSupportKorean;
@property (nonatomic, readonly) BOOL isSupportGerman;
@property (nonatomic, readonly) BOOL isSupportFrench;
@property (nonatomic, readonly) BOOL isSupportSpanish;
@property (nonatomic, readonly) BOOL isSupportArabic;
@property (nonatomic, readonly) BOOL isSupportRussian;
@property (nonatomic, readonly) BOOL isSupportTraditionalChinese;
@property (nonatomic, readonly) BOOL isSupportItalian;
@property (nonatomic, readonly) BOOL isSupportPortuguese;
@property (nonatomic, readonly) BOOL isSupportUkrainian;
@property (nonatomic, readonly) BOOL isSupportHindi;
@property (nonatomic, readonly) BOOL isSupportPolish;
@property (nonatomic, readonly) BOOL isSupportGreek;
@property (nonatomic, readonly) BOOL isSupportVietnamese;
@property (nonatomic, readonly) BOOL isSupportIndonesian;
@property (nonatomic, readonly) BOOL isSupportThai;
@property (nonatomic, readonly) BOOL isSupportDutch;
@property (nonatomic, readonly) BOOL isSupportTurkish;
@property (nonatomic, readonly) BOOL isSupportRomanian;
@property (nonatomic, readonly) BOOL isSupportDanish;
@property (nonatomic, readonly) BOOL isSupportSwedish;
@property (nonatomic, readonly) BOOL isSupportCzech;
@property (nonatomic, readonly) BOOL isSupportBengali;
@property (nonatomic, readonly) BOOL isSupportPersian;
@property (nonatomic, readonly) BOOL isSupportHebrew;
@property (nonatomic, readonly) BOOL isSupportMalay;
@property (nonatomic, readonly) BOOL isSupportSlovak;
@property (nonatomic, readonly) BOOL isSupportXhosa;
@property (nonatomic, readonly) BOOL isSupportSlovenian;
@property (nonatomic, readonly) BOOL isSupportHungarian;
@property (nonatomic, readonly) BOOL isSupportLithuanian;
@property (nonatomic, readonly) BOOL isSupportUrdu;
@property (nonatomic, readonly) BOOL isSupportBulgarian;
@property (nonatomic, readonly) BOOL isSupportCroatian;
@property (nonatomic, readonly) BOOL isSupportLatvian;
@property (nonatomic, readonly) BOOL isSupportEstonian;
@property (nonatomic, readonly) BOOL isSupportKhmer;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK25ZyFunctionModel_localDial")
@interface ZyFunctionModel_localDial : NSObject
@property (nonatomic, readonly) NSInteger maxDialCount;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK28ZyFunctionModel_notification")
@interface ZyFunctionModel_notification : NSObject
@property (nonatomic, readonly) BOOL isSupportCall;
@property (nonatomic, readonly) BOOL isSupportSMS;
@property (nonatomic, readonly) BOOL isSupportInstagram;
@property (nonatomic, readonly) BOOL isSupportWechat;
@property (nonatomic, readonly) BOOL isSupportQQ;
@property (nonatomic, readonly) BOOL isSupportLine;
@property (nonatomic, readonly) BOOL isSupportLinkedIn;
@property (nonatomic, readonly) BOOL isSupportWhatsApp;
@property (nonatomic, readonly) BOOL isSupportTwitter;
@property (nonatomic, readonly) BOOL isSupportFacebook;
@property (nonatomic, readonly) BOOL isSupportMessenger;
@property (nonatomic, readonly) BOOL isSupportSkype;
@property (nonatomic, readonly) BOOL isSupportSnapchat;
@property (nonatomic, readonly) BOOL isSupportExtensionNotification;
@property (nonatomic, readonly) BOOL isSupportAlipay;
@property (nonatomic, readonly) BOOL isSupportTaoBao;
@property (nonatomic, readonly) BOOL isSupportDouYin;
@property (nonatomic, readonly) BOOL isSupportDingDing;
@property (nonatomic, readonly) BOOL isSupportJingDong;
@property (nonatomic, readonly) BOOL isSupportGmail;
@property (nonatomic, readonly) BOOL isSupportViber;
@property (nonatomic, readonly) BOOL isSupportYouTube;
@property (nonatomic, readonly) BOOL isSupportKakaoTalk;
@property (nonatomic, readonly) BOOL isSupportTelegram;
@property (nonatomic, readonly) BOOL isSupportHangouts;
@property (nonatomic, readonly) BOOL isSupportVkontakte;
@property (nonatomic, readonly) BOOL isSupportFlickr;
@property (nonatomic, readonly) BOOL isSupportTumblr;
@property (nonatomic, readonly) BOOL isSupportPinterest;
@property (nonatomic, readonly) BOOL isSupportTruecaller;
@property (nonatomic, readonly) BOOL isSupportPaytm;
@property (nonatomic, readonly) BOOL isSupportZalo;
@property (nonatomic, readonly) BOOL isSupportMicrosoftTeams;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK28ZyFunctionModel_platformType")
@interface ZyFunctionModel_platformType : NSObject
@property (nonatomic, readonly) NSInteger platform;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK29ZyFunctionModel_screenControl")
@interface ZyFunctionModel_screenControl : NSObject
@property (nonatomic, readonly) NSInteger screenLevelCount;
@property (nonatomic, readonly) NSInteger screenTimeLong_max;
@property (nonatomic, readonly) NSInteger screenTimeLong_min;
@property (nonatomic, readonly) NSInteger screenTimeLong_interval;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK26ZyFunctionModel_scrrenType")
@interface ZyFunctionModel_scrrenType : NSObject
@property (nonatomic, readonly) NSInteger supportType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK30ZyFunctionModel_sportCountdown")
@interface ZyFunctionModel_sportCountdown : NSObject
@property (nonatomic, readonly) NSInteger countDownTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK47ZyFunctionModel_supportMeasurementDataTypeModel")
@interface ZyFunctionModel_supportMeasurementDataTypeModel : NSObject
@property (nonatomic, readonly) BOOL isSupportSingleClickData;
@property (nonatomic, readonly) BOOL isSupportAllDayData;
@property (nonatomic, readonly) NSInteger singleClickDataCount;
@property (nonatomic, readonly) NSInteger allDayDataTimeInterval;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK41ZyFunctionModel_supportMusicFileTypeModel")
@interface ZyFunctionModel_supportMusicFileTypeModel : NSObject
@property (nonatomic) BOOL isSupportMp3;
@property (nonatomic) BOOL isSupportWav;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5ZySDK9ZyHrModel")
@interface ZyHrModel : NSObject
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull detailArray;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5ZySDK15ZyHrWaringModel")
@interface ZyHrWaringModel : NSObject
@property (nonatomic) BOOL isOpen;
@property (nonatomic) NSInteger maxValue;
@property (nonatomic) NSInteger minValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZyLanguageType, open) {
  ZyLanguageTypeEnglish = 0,
  ZyLanguageTypeSimplifiedChinese = 1,
  ZyLanguageTypeJapanese = 2,
  ZyLanguageTypeKorean = 3,
  ZyLanguageTypeGerman = 4,
  ZyLanguageTypeFrench = 5,
  ZyLanguageTypeSpanish = 6,
  ZyLanguageTypeArabic = 7,
  ZyLanguageTypeRussian = 8,
  ZyLanguageTypeTraditionalChinese = 9,
  ZyLanguageTypeItalian = 10,
  ZyLanguageTypePortuguese = 11,
  ZyLanguageTypeUkrainian = 12,
  ZyLanguageTypeHindi = 13,
};


SWIFT_CLASS("_TtC5ZySDK18ZyLedFunctionModel")
@interface ZyLedFunctionModel : NSObject
@property (nonatomic) enum ZyLedFunctionType ledType;
@property (nonatomic) NSInteger ledColor;
@property (nonatomic) NSInteger firstColor;
@property (nonatomic) NSInteger secondColor;
@property (nonatomic) NSInteger thirdColor;
@property (nonatomic) NSInteger timeLength;
@property (nonatomic) NSInteger frequency;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDic:(NSDictionary<NSString *, id> * _Nonnull)dic OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZyLedFunctionType, open) {
  ZyLedFunctionTypeUnknow = -1,
  ZyLedFunctionTypePowerIndicator = 0,
  ZyLedFunctionTypeInformationReminder = 1,
  ZyLedFunctionTypeBtBind = 2,
  ZyLedFunctionTypeStepCountingStandardReminder = 3,
  ZyLedFunctionTypeLowBatteryReminder = 4,
};


SWIFT_CLASS("_TtC5ZySDK17ZyLowBatteryModel")
@interface ZyLowBatteryModel : NSObject
@property (nonatomic) BOOL isOpen;
@property (nonatomic) NSInteger remindBattery;
@property (nonatomic) NSInteger remindCount;
@property (nonatomic) NSInteger remindInterval;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ZyMeasurementType : NSInteger;
@class ZyMeasurementValueModel;

SWIFT_CLASS("_TtC5ZySDK18ZyMeasurementModel")
@interface ZyMeasurementModel : NSObject
@property (nonatomic) enum ZyMeasurementType type;
@property (nonatomic) NSInteger timeInterval;
@property (nonatomic, copy) NSArray<ZyMeasurementValueModel *> * _Nonnull listArray;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZyMeasurementType, open) {
  ZyMeasurementTypeHeartrate = 1,
  ZyMeasurementTypeBloodOxygen = 2,
  ZyMeasurementTypeBloodPressure = 3,
  ZyMeasurementTypeBloodSugar = 4,
  ZyMeasurementTypePressure = 5,
  ZyMeasurementTypeBodyTemperature = 6,
  ZyMeasurementTypeElectrocardiogram = 7,
};


SWIFT_CLASS("_TtC5ZySDK23ZyMeasurementValueModel")
@interface ZyMeasurementValueModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull time;
@property (nonatomic) NSInteger value_1;
@property (nonatomic) NSInteger value_2;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5ZySDK16ZyMenstrualModel")
@interface ZyMenstrualModel : NSObject
@property (nonatomic) BOOL isOpen;
@property (nonatomic) NSInteger cycleCount;
@property (nonatomic) NSInteger menstrualCount;
@property (nonatomic) NSInteger year;
@property (nonatomic) NSInteger month;
@property (nonatomic) NSInteger day;
@property (nonatomic) NSInteger advanceDay;
@property (nonatomic) NSInteger remindHour;
@property (nonatomic) NSInteger remindMinute;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5ZySDK20ZyMotorFunctionModel")
@interface ZyMotorFunctionModel : NSObject
@property (nonatomic) enum ZyLedFunctionType ledType;
@property (nonatomic) NSInteger timeLength;
@property (nonatomic) NSInteger frequency;
@property (nonatomic) NSInteger level;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithDic:(NSDictionary<NSString *, id> * _Nonnull)dic OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZyNotificationExtensionType, open) {
  ZyNotificationExtensionTypeAlipay = 0,
  ZyNotificationExtensionTypeTaoBao = 1,
  ZyNotificationExtensionTypeDouYin = 2,
  ZyNotificationExtensionTypeDingDing = 3,
  ZyNotificationExtensionTypeJingDong = 4,
  ZyNotificationExtensionTypeGmail = 5,
  ZyNotificationExtensionTypeViber = 6,
  ZyNotificationExtensionTypeYouTube = 7,
  ZyNotificationExtensionTypeKakaoTalk = 8,
  ZyNotificationExtensionTypeTelegram = 9,
  ZyNotificationExtensionTypeHangouts = 10,
  ZyNotificationExtensionTypeVkontakte = 11,
  ZyNotificationExtensionTypeFlickr = 12,
  ZyNotificationExtensionTypeTumblr = 13,
  ZyNotificationExtensionTypePinterest = 14,
  ZyNotificationExtensionTypeTruecaller = 15,
  ZyNotificationExtensionTypePaytm = 16,
  ZyNotificationExtensionTypeZalo = 17,
  ZyNotificationExtensionTypeMicrosoftTeams = 18,
};

typedef SWIFT_ENUM(NSInteger, ZyNotificationType, open) {
  ZyNotificationTypeCall = 1,
  ZyNotificationTypeSMS = 2,
  ZyNotificationTypeInstagram = 3,
  ZyNotificationTypeWechat = 4,
  ZyNotificationTypeQQ = 5,
  ZyNotificationTypeLine = 6,
  ZyNotificationTypeLinkedIn = 7,
  ZyNotificationTypeWhatsApp = 8,
  ZyNotificationTypeTwitter = 9,
  ZyNotificationTypeFacebook = 10,
  ZyNotificationTypeMessenger = 11,
  ZyNotificationTypeSkype = 12,
  ZyNotificationTypeSnapchat = 13,
  ZyNotificationTypeExtensionNotificationType = 14,
  ZyNotificationTypeOther = 15,
};


SWIFT_CLASS("_TtC5ZySDK17ZyOnlineDialModel")
@interface ZyOnlineDialModel : NSObject
@property (nonatomic) NSInteger dialId;
@property (nonatomic, copy) NSString * _Nullable dialImageUrl;
@property (nonatomic, copy) NSString * _Nullable dialFileUrl;
@property (nonatomic, copy) NSString * _Nullable dialName;
@property (nonatomic, copy) NSString * _Nullable dialPreviewUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5ZySDK15ZyPersonalModel")
@interface ZyPersonalModel : NSObject
@property (nonatomic) NSInteger age;
@property (nonatomic) BOOL gender;
@property (nonatomic) float height;
@property (nonatomic) float weight;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZyPositionShowType, open) {
  ZyPositionShowTypeClose = 0,
  ZyPositionShowTypeDate = 1,
  ZyPositionShowTypeSleep = 2,
  ZyPositionShowTypeHeartrate = 3,
  ZyPositionShowTypeStep = 4,
};

typedef SWIFT_ENUM(NSInteger, ZyPositionType, open) {
  ZyPositionTypeLeftTop = 0,
  ZyPositionTypeLeftMiddle = 1,
  ZyPositionTypeLetfBottom = 2,
  ZyPositionTypeRightTop = 3,
  ZyPositionTypeRightMiddle = 4,
  ZyPositionTypeRightBottom = 5,
  ZyPositionTypeCenterTop = 6,
  ZyPositionTypeCenterMiddle = 7,
  ZyPositionTypeCenterBottom = 8,
};


SWIFT_CLASS("_TtC5ZySDK8ZySDKLog")
@interface ZySDKLog : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (void)writeStringToSDKLogWithString:(NSString * _Nonnull)string;
+ (NSString * _Nonnull)showLog SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)showAllLog SWIFT_WARN_UNUSED_RESULT;
+ (void)clear;
@end


SWIFT_CLASS("_TtC5ZySDK11ZyScanModel")
@interface ZyScanModel : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) NSInteger rssi;
@property (nonatomic, strong) CBPeripheral * _Nullable peripheral;
@property (nonatomic, copy) NSString * _Nullable uuidString;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5ZySDK16ZySedentaryModel")
@interface ZySedentaryModel : NSObject
@property (nonatomic) BOOL isOpen;
@property (nonatomic) NSInteger timeLong;
@property (nonatomic, copy) NSArray<ZyStartEndTimeModel *> * _Nonnull timeArray;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5ZySDK12ZySleepModel")
@interface ZySleepModel : NSObject
@property (nonatomic) NSInteger deep;
@property (nonatomic) NSInteger light;
@property (nonatomic) NSInteger awake;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, NSString *> *> * _Nonnull detailArray;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, NSString *> *> * _Nonnull detailArray_filter;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5ZySDK19ZyStartEndTimeModel")
@interface ZyStartEndTimeModel : NSObject
@property (nonatomic) NSInteger startHour;
@property (nonatomic) NSInteger startMinute;
@property (nonatomic) NSInteger endHour;
@property (nonatomic) NSInteger endMinute;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5ZySDK11ZyStepModel")
@interface ZyStepModel : NSObject
@property (nonatomic) NSInteger step;
@property (nonatomic) NSInteger calorie;
@property (nonatomic) NSInteger distance;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull detailArray;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ZyWeatherType : NSInteger;

SWIFT_CLASS("_TtC5ZySDK14ZyWeatherModel")
@interface ZyWeatherModel : NSObject
@property (nonatomic) NSInteger dayCount;
@property (nonatomic) enum ZyWeatherType type;
@property (nonatomic) NSInteger temp;
@property (nonatomic) NSInteger airQuality;
@property (nonatomic) NSInteger minTemp;
@property (nonatomic) NSInteger maxTemp;
@property (nonatomic) NSInteger tomorrowMinTemp;
@property (nonatomic) NSInteger tomorrowMaxTemp;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZyWeatherType, open) {
  ZyWeatherTypeOvercast = 0,
  ZyWeatherTypeFog = 1,
  ZyWeatherTypeSunny = 2,
  ZyWeatherTypeCloudy = 3,
  ZyWeatherTypeSnow = 4,
  ZyWeatherTypeRain = 5,
};


SWIFT_CLASS("_TtC5ZySDK18ZyWorshipTimeModel")
@interface ZyWorshipTimeModel : NSObject
@property (nonatomic, copy) NSString * _Nonnull timeString;
@property (nonatomic) NSInteger fajr;
@property (nonatomic) NSInteger sunrise;
@property (nonatomic) NSInteger dhuhr;
@property (nonatomic) NSInteger asr;
@property (nonatomic) NSInteger maghrib;
@property (nonatomic) NSInteger isha;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
