# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'ZySdkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZySdkDemo
  pod 'Alamofire'

  target 'ZySdkDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZySdkDemoUITests' do
    # Pods for testing
  end

end
