# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'AntSdkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AntSdkDemo
  pod 'Alamofire'
#  pod 'MZRSA_Swift'

  target 'AntSdkDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AntSdkDemoUITests' do
    # Pods for testing
  end

end
